### ISSUE TITLE
Connect master branch to AWS Amplify or Netlify

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#47]
Engramar would like this project to be a live development environment. This will act as a live staging area, directly updated from the master branch.

**Comment by kimchirice** [comment]
@QjStout g'day. have you started this task? I have been working with netlify a bit, and almost done with the route/nav issue. let me pick it up if it's OK.

**Comment by QjStout** [comment]
Hey @kimchirice, I'm going to do this one man. It won't take me long, I just haven't had a chance to get to it yet.
I've cleared out most of my To Do list so this is a high priority now.

**Comment by QjStout** [comment]
Not going with AWS. There is no ability to set hard budget limits and I could rack up 10's of thousands in debt in less than an hour.

**Comment by kimchirice** [comment]
cool, man.  I reckon going forward with Netlify is what we need at the moment.

**Comment by QjStout** [comment]
Hey @kimchirice, passing this to you now if that's okay still

**Comment by kimchirice** [comment]
I will set this with higher priority, comparing to issue #52 @QjStout @engramar

**Comment by QjStout** [comment]
Thanks @kimchirice, I appreciate it.

**Comment by engramar** [comment]
Sounds good, @kimchirice. Thanks.

**Comment by kimchirice** [comment]
hello @QjStout and @engramar

sorry for the late update. Engramar and myself worked together yesterday, and managed to have our repo built and hosted on the [Netlify](https://code-dot-sydney.netlify.app/ ). 

it seems has been working OK since then.

- screen record 
![Screen Shot 2020-08-02 at 20 09 44](https://user-images.githubusercontent.com/36904351/89120773-3a1c4600-d4fc-11ea-8fb6-fff7ab118dbd.png)

#### NOTE
   *the deployment on Netlify is done with my personal account, after discussed with Engramar, we agreed to process this with my personal account for now. once we sort out the other issue of CI assigned to me, we will then transfer the ownership to Engramar*

for this stag, it is OK to close this issue. what do you gents think?

**Comment by QjStout** [comment]
Looks good @kimchirice.
We just need to figure out that JSON data service now so the member profiles will work

**Comment by QjStout** [comment]
I think we are good to close this @kimchirice
